services:
 weaviate:
   image: cr.weaviate.io/semitechnologies/weaviate:1.31.0
   restart: on-failure:0
   ports:
     - 9090:8080
     - 50051:50051
   volumes:
     - weaviate_data:/var/lib/weaviate
   environment:
     QUERY_DEFAULTS_LIMIT: 25
     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
     AUTHENTICATION_APIKEY_ENABLED: 'true'
     AUTHENTICATION_APIKEY_ALLOWED_KEYS: '189143d91a5b25e2'
     AUTHENTICATION_APIKEY_USERS: 'admin'
     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
     DEFAULT_VECTORIZER_MODULE: text2vec-transformers
     ENABLE_MODULES: text2vec-transformers
     TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
     CLUSTER_HOSTNAME: 'node1'
   depends_on:
     - t2v-transformers

 t2v-transformers:
   image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-mpnet-base-v2
   environment:
     ENABLE_CUDA: 0
   ports:
     - 9089:8080
   deploy:
     resources:
       limits:
         memory: 4G
       reservations:
         memory: 3G

volumes:
 weaviate_data: